call runDemo concordance/RunGoPConcordance GoPConcordance 1 bible 8
call runDemo concordance/RunGoPConcordance GoPConcordance 2 bible 8
call runDemo concordance/RunGoPConcordance GoPConcordance 4 bible 8
call runDemo concordance/RunGoPConcordance GoPConcordance 8 bible 8
call runDemo concordance/RunGoPConcordance GoPConcordance 16 bible 8
call runDemo concordance/RunGoPConcordance GoPConcordance 32 bible 8
call runDemo concordance/RunGoPConcordance GoPConcordance 1 2bibles 8
call runDemo concordance/RunGoPConcordance GoPConcordance 2 2bibles 8
call runDemo concordance/RunGoPConcordance GoPConcordance 4 2bibles 8
call runDemo concordance/RunGoPConcordance GoPConcordance 8 2bibles 8
call runDemo concordance/RunGoPConcordance GoPConcordance 16 2bibles 8
call runDemo concordance/RunGoPConcordance GoPConcordance 32 2bibles 8
call runDemo concordance/RunGoPConcordance GoPConcordance 1 4bibles 8
call runDemo concordance/RunGoPConcordance GoPConcordance 2 4bibles 8
call runDemo concordance/RunGoPConcordance GoPConcordance 4 4bibles 8
call runDemo concordance/RunGoPConcordance GoPConcordance 8 4bibles 8
call runDemo concordance/RunGoPConcordance GoPConcordance 16 4bibles 8
call runDemo concordance/RunGoPConcordance GoPConcordance 32 4bibles 8
call runDemo concordance/RunGoPConcordance GoPConcordance 1 bible 16
call runDemo concordance/RunGoPConcordance GoPConcordance 2 bible 16
call runDemo concordance/RunGoPConcordance GoPConcordance 4 bible 16
call runDemo concordance/RunGoPConcordance GoPConcordance 8 bible 16
call runDemo concordance/RunGoPConcordance GoPConcordance 16 bible 16
call runDemo concordance/RunGoPConcordance GoPConcordance 32 bible 16
call runDemo concordance/RunGoPConcordance GoPConcordance 1 2bibles 16
call runDemo concordance/RunGoPConcordance GoPConcordance 2 2bibles 16
call runDemo concordance/RunGoPConcordance GoPConcordance 4 2bibles 16
call runDemo concordance/RunGoPConcordance GoPConcordance 8 2bibles 16
call runDemo concordance/RunGoPConcordance GoPConcordance 16 2bibles 16
call runDemo concordance/RunGoPConcordance GoPConcordance 32 2bibles 16
call runDemo concordance/RunGoPConcordance GoPConcordance 1 4bibles 16
call runDemo concordance/RunGoPConcordance GoPConcordance 2 4bibles 16
call runDemo concordance/RunGoPConcordance GoPConcordance 4 4bibles 16
call runDemo concordance/RunGoPConcordance GoPConcordance 8 4bibles 16
call runDemo concordance/RunGoPConcordance GoPConcordance 16 4bibles 16
call runDemo concordance/RunGoPConcordance GoPConcordance 32 4bibles 16
call runDemo concordance/RunGoPConcordance GoPConcordance 1 bible 32
call runDemo concordance/RunGoPConcordance GoPConcordance 2 bible 32
call runDemo concordance/RunGoPConcordance GoPConcordance 4 bible 32
call runDemo concordance/RunGoPConcordance GoPConcordance 8 bible 32
call runDemo concordance/RunGoPConcordance GoPConcordance 16 bible 32
call runDemo concordance/RunGoPConcordance GoPConcordance 32 bible 32
call runDemo concordance/RunGoPConcordance GoPConcordance 1 2bibles 32
call runDemo concordance/RunGoPConcordance GoPConcordance 2 2bibles 32
call runDemo concordance/RunGoPConcordance GoPConcordance 4 2bibles 32
call runDemo concordance/RunGoPConcordance GoPConcordance 8 2bibles 32
call runDemo concordance/RunGoPConcordance GoPConcordance 16 2bibles 32
call runDemo concordance/RunGoPConcordance GoPConcordance 32 2bibles 32
call runDemo concordance/RunGoPConcordance GoPConcordance 1 4bibles 32
call runDemo concordance/RunGoPConcordance GoPConcordance 2 4bibles 32
call runDemo concordance/RunGoPConcordance GoPConcordance 4 4bibles 32
call runDemo concordance/RunGoPConcordance GoPConcordance 8 4bibles 32
call runDemo concordance/RunGoPConcordance GoPConcordance 16 4bibles 32
call runDemo concordance/RunGoPConcordance GoPConcordance 32 4bibles 32
